on:
  push:
    branches:
      - "**"

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: gonsuke/gha-custom-action-ts-sample@main
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        with:
          run: |
            echo "hello"
