on:
  push:
    branches:
      - "**"

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: gonsuke/gha-custom-action-ts-sample@main
        with:
          run: |
            echo "hello"

